services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:2.9.0
    container_name: n8n-local-dev
    ports:
      - "5680:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
      - NODE_ENV=development
    volumes:
      - n8n_data:/home/node/.n8n
      - ./:/home/node/.n8n/custom/node_modules/n8n-nodes-gcp-storage
    restart: unless-stopped

volumes:
  n8n_data:
